### ISSUE TITLE
心跳错误:end of input at character 0 of

### ISSUE THREAD

**Issue by kuangxiaoye** [shinian-a/Vmq-App#7]
心跳错误:end of input at character 0 of

请问这是什么原因呢··卸载重装也一样···

**Comment by shinian-a** [comment]
网站请勿使用cdn或者VPN不管是网站还是本地网络！

**Comment by kuangxiaoye** [comment]
> 网站请勿使用cdn或者VPN不管是网站还是本地网络！
感谢帮助 已经解决，的确是这个原因
